FROM luckyj/php-7.4-kafka:latest

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user with correct gid and uid
ARG PUID
ARG PGID
RUN groupadd -g ${PGID} printhero && \
    useradd -u ${PUID} -g printhero -s /bin/bash -m printhero

USER printhero

WORKDIR /var/www/html
