version: '3.7'

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - ${POSTGRES_PORT:-5432}:5432
    networks:
      - hp

networks:
  hp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.29.1.0/24"