version: '3.7'

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - ${POSTGRES_PORT:-5432}:5432
    networks:
      - hp

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - ${ZOOKEEPER_PORT:-2181}:2181
    networks:
      - hp

  kafka:
    image: "wurstmeister/kafka:2.12-2.5.0"
    ports:
      - ${KAFKA_ADVERTISED_PORT:-9092}:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT: ${KAFKA_ADVERTISED_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
    depends_on:
      - zookeeper
    networks:
      - hp

  service-a:
    build:
      context: src/service_a
      dockerfile: docker/Dockerfile
    depends_on:
      - kafka
    networks:
      - hp

  service-b:
    build:
      context: src/service_b
      dockerfile: docker/Dockerfile
    depends_on:
      - kafka
    networks:
      - hp

  broker:
    build:
      context: src/broker
      dockerfile: docker/Dockerfile
    depends_on:
      - kafka
      - db
    networks:
      - hp

  requester:
    build:
      context: src/requester
      dockerfile: docker/Dockerfile
    depends_on:
      - broker
      - nginx
    networks:
      - hp

  nginx:
    image: nginx:1.11-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./src/broker/src:/var/www/html
    depends_on:
      - broker
    networks:
      - hp

networks:
  hp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.29.1.0/24"